from rest_framework import serializers


class EmpleadoSerializer(serializers.Serializer):
    Id_Empleado = serializers.CharField()
    No_CI = serializers.CharField()
    Nombre = serializers.CharField()
    Apellido_1 = serializers.CharField()
    Apellido_2 = serializers.CharField()
    Baja = serializers.BooleanField()
    Alta = serializers.BooleanField()
    Id_Cargo = serializers.CharField()
    Id_Direccion = serializers.CharField()
    Sexo = serializers.CharField()
    Id_Provincia = serializers.CharField()
    Id_Municipio = serializers.CharField()
    Docente = serializers.BooleanField()
    Id_Categoria_DI = serializers.CharField()
    Id_Grado_Cientifico = serializers.CharField()
    Desc_Provincia = serializers.CharField(required=False)
    Desc_Municipio = serializers.CharField(required=False)
    Desc_Direccion = serializers.CharField(required=False)
    Desc_Cargo = serializers.CharField(required=False)
    Desc_Categoria_DI = serializers.CharField(required=False)
    Desc_Grado_Cientifico = serializers.CharField(required=False)
